### ISSUE TITLE
16.2版本，点赞数据无法保存

### ISSUE THREAD

**Issue by smartmimi** [2kuai/Surge#1]
可以正常去广告、下载无水印。
但是点击红心赞之后，无法保存数据。

**Comment by 2kuai** [comment]
很抱歉，由于该Bug无法复现，如需继续得到帮助，请回复详细说明。

**Comment by smartmimi** [comment]
录屏 https://telegra.ph/%E5%BD%95%E5%B1%8F-08-17
同时也有surge抓包数据，以及转制的Thor格式数据
[f4thor.zip](https://github.com/2kuai/Surge/files/7000352/f4thor.zip)
[2021-08-17-212350.surgearchive.zip](https://github.com/2kuai/Surge/files/7000354/2021-08-17-212350.surgearchive.zip)

**Comment by smartmimi** [comment]
并不能稳定复现，有时候会一直不能保存“点赞”数据，有时候却又可以，找不出规律来。抓包数据看不懂。
刚才在录制是，有几率在开启录屏、开启抓包等动作后，突然恢复正常，可以点赞，但也不能稳定复现。
无法判断到底是因为什么原因触发的。

**Comment by 2kuai** [comment]
已查明原因，系近期点赞过于频繁，一段时间后即可恢复正常。

**Comment by smartmimi** [comment]
多谢。
很奇怪的原因。原来是抖音自己的锅啊。
